#!/bin/sh
set -e

usage() {
  echo "$0 <class>"
  echo 'Available classes:'
  list_classes | sed 's|^|  - |'
  exit 1
}

list_classes() {
  echo IndexStorageBarrel
  echo Downloader
  echo Gateway
  echo Client
  echo JsoupDemo
  echo Url
}

mvn_args=

for arg
do
  case "$arg" in
    -h | --help) usage ;;
    --debug)
      mvn_args="$mvn_args --debug"
      shift
      ;;
  esac
done

class="$1"

list_classes | grep --quiet "^$class$" || usage

case "$class" in
  IndexStorageBarrel | Gateway)
    (
    tput smcup
    clear
    java -cp target/googol-1.0-SNAPSHOT.jar com.googol."$class"
    tput rmcup
    )
    ;;
  Downloader | Client | JsoupDemo | Url)
    (
    tput smcup
    clear
    # shellcheck disable=SC2086
    mvn exec:java $mvn_args --quiet --offline --define=exec.mainClass=com.googol."$class"
    tput rmcup
    )
    ;;
  *)
    usage
    ;;
esac
